### ISSUE TITLE
Integer values in policy definition fails to create policy

### ISSUE THREAD

**Issue by kishorenc** [terraform-providers/terraform-provider-rabbitmq#12]
### Terraform Version
```
Terraform v0.11.1
+ provider.rabbitmq v0.2.0
```
### Affected Resource(s)

- `rabbitmq_policy`

### Terraform Configuration Files

```
resource "rabbitmq_policy" "limit-pollingnode" {
  provider = "rabbitmq.rabbitnode"
  name     = "limit queue"
  vhost    = "main"

  policy {
    pattern  = "^queue"
    priority = 0
    apply_to = "queues"

    definition {
      max-length = 10000
    }
  }
}
```

Plan:

```
+ module.rabbit-v6-resources.rabbitmq_policy.limit-queue
      id:                             <computed>
      name:                           "limit queue"
      policy.#:                       "1"
      policy.0.apply_to:              "queues"
      policy.0.definition.%:          "1"
      policy.0.definition.max-length: "10000"
      policy.0.pattern:               "^queue"
      policy.0.priority:              "0"
      vhost:                          "main"
```

### Expected Behavior

The policy should be created.

### Actual Behavior

Failed to apply the plan with the error message:

```
module.rabbit-v6-resources.rabbitmq_policy.limit-queue: Creating...
  name:                           "" => "limit queue"
  policy.#:                       "" => "1"
  policy.0.apply_to:              "" => "queues"
  policy.0.definition.%:          "" => "1"
  policy.0.definition.max-length: "" => "10000"
  policy.0.pattern:               "" => "^queue"
  policy.0.priority:              "" => "0"
  vhost:                          "" => "main"
Releasing state lock. This may take a few moments...

Error: Error applying plan:

1 error(s) occurred:

* module.rabbit-v6-resources.rabbitmq_policy.limit-queue: 1 error(s) occurred:

* rabbitmq_policy.limit-queue: Error declaring RabbitMQ policy: 400 Bad Request
```

### References

Very similar to: https://github.com/terraform-providers/terraform-provider-rabbitmq/issues/1

The`max-length` is probably sent as a string, while it is expected to be of type integer by Rabbit.

**Comment by jtopjian** [comment]
@kishorenc Thank you for reporting this.

I think you're right about this being similar to #1. I've reviewed the rabbit docs and I see enough examples of policy definitions using integers that it wouldn't be possible (or very easy) to account for _all_ definition keys that take an integer. So a free-form JSON option is probably best here.

**Comment by jtopjian** [comment]
hmm... after reviewing this, free-form JSON might be difficult. There is already a measure that was put in place to handle HA policies that specify an array of nodes. Accounting for the use-case when someone wanted to apply _both_ an HA policy and a policy which had an integer value will cause some trouble.

The best solution here might be to see if the string value looks like a number.

I'll get a PR for this in the next day or two for review.
