### ISSUE TITLE
Tag master as a new release?

### ISSUE THREAD

**Issue by greggilbert** [terraform-providers/terraform-provider-rabbitmq#14]
Hi all, really quick: we just hit an issue that will likely be resolved by 2f5f98f. Would it be possible to tag master as the latest release, or is there something else holding this up?

**Comment by jtopjian** [comment]
@greggilbert The delay is my fault. I'm going to try to get #13 reviewed and merged soon and then we'll have a release with both fixes.

I apologize for the delay.

**Comment by jtopjian** [comment]
@greggilbert version 1.0.0 was released a few minutes ago. Please let me know if you have any questions or problems with it.
