### ISSUE TITLE
Documentation for rabbitmq_policy resource

### ISSUE THREAD

**Issue by tpreviero** [terraform-providers/terraform-provider-rabbitmq#22]
Hi there 👋

I've been noticing (I've spent some time crushing my head on it) that the required `apply_to` parameter of the `rabbitmq_policy` in the `policy` node that is documented as
`Can either be "exchange", "queues", or "all".`
should actually be
`Can either be "exchanges", "queues", or "all".`

Otherwise you'll get a Bad Request (400) at creation time when focusing exchanges.

Sorry to be so pedantic 🙃 
Thank you,

Tommaso

**Comment by jtopjian** [comment]
> Sorry to be so pedantic

No apologies needed! I've just fixed this typo. We'll get it published soon.
