### ISSUE TITLE
Support for client certificate authentication

### ISSUE THREAD

**Issue by kuffel** [terraform-providers/terraform-provider-rabbitmq#24]
Hi there,

are there any plans for supporting client certificate authentication?
Or is there an undocumented argument to provide a client certificate?

https://www.terraform.io/docs/providers/rabbitmq/index.html

Kind regards,
Adam

**Comment by sam-dumont** [comment]
Hi Adam,

I just opened a pull request following this and there is a binary available at https://github.com/samueldumont/terraform-provider-rabbitmq/releases

There is no support for passphrase protected keys but I can add it if needed
