### ISSUE TITLE
provider does not seem to abide by the https_proxy setting

### ISSUE THREAD

**Issue by jcarrothers-sap** [terraform-providers/terraform-provider-rabbitmq#28]
### Terraform Version
Terraform: v0.11.13
terraform-provider-rabbitmq: v1.0.0

### Affected Resource(s)
rabbitmq_policy (likely others as well, but not tested)

### Expected Behavior
When an `https_proxy` setting is provided by the environment (on Linux), the provider should use the configured proxy to access the RabbitMQ endpoints.

### Actual Behavior
The provider still attempts to access the RabbitMQ API endpoints directly.

**Comment by aminueza** [comment]
This issue can be closed. Issue related to #39

**Comment by cyrilgdn** [comment]
@aminueza Indeed, thanks :) !

@jcarrothers-sap FYI, this will be released in the next day (in v1.3.0)
