### ISSUE TITLE
Support for Terraform v0.12

### ISSUE THREAD

**Issue by bducharme** [terraform-providers/terraform-provider-rabbitmq#33]
Hi, is there any plan to support Terraform v0.12 in the upcoming weeks?

Thanks

**Comment by ghost** [comment]
Just followed the [upgrade guide](https://www.terraform.io/docs/extend/terraform-0.12-compatibility.html) and copied the resulting binary to `.terraform/plugins/linux_amd64/` and everything works.

```
go get github.com/hashicorp/terraform@v0.12.0
go mod tidy
go mod vendor
go build
```

It seems there is little (technical) reason to delay an update for 0.12?
