### ISSUE TITLE
Document RABBITMQ_ENDPOINT, RABBITMQ_USERNAME, and RABBITMQ_PASSWORD

### ISSUE THREAD

**Issue by sciurus** [terraform-providers/terraform-provider-rabbitmq#35]
Currently the documentation for setting the endpoint, username, and password only explains how to do it in your HCL, e.g.

```
provider "rabbitmq" {
  endpoint = "http://127.0.0.1"
  username = "guest"
  password = "guest"
}
```

From checking the code and testing, I've realized you can also set them by leaving them out of the provider definition and exporting environment variables instead. This should be documented. Using the environment variables makes it easier to keep secrets our of your repo and to apply the same terraform across environments.

**Comment by cyrilgdn** [comment]
@sciurus Done by @aminueza in #50
