### ISSUE TITLE
Add federation resource

### ISSUE THREAD

**Issue by barryib** [terraform-providers/terraform-provider-rabbitmq#43]
It would be great if we can manage RabbitMQ federations with this provider

**Comment by cyrilgdn** [comment]
Forgot to close this one but [federation resource](https://www.terraform.io/docs/providers/rabbitmq/r/federation-upstream.html) has been released in [v1.4.0](https://github.com/terraform-providers/terraform-provider-rabbitmq/blob/master/CHANGELOG.md#140-july-17-2020)
