### ISSUE TITLE
Consider allow arguments_json in rabbitmq_binding just like the already existing for rabbitmq_queue 

### ISSUE THREAD

**Issue by dnp1** [terraform-providers/terraform-provider-rabbitmq#56]
Currently I'm using terraform to specify my rabbit_mq broker.

One interesting fact is that I could not found how use lists in binding arguments.
This is an importante feature because I have a federation where many messages are useless to my queues and I would like to filter using a small set of values against a header param.

Looking at the docs I found rabbitmq_queue currently supports json arguments.

Why not extend this behaviour though the provider, making this possible for every entity like binding?

**Comment by dnp1** [comment]
Can anyone help me here? 
Whenever the type of my key value, my bind arguments are always string.

The exchange I'm federated to is not mine and the headers I need to filters are number. So it would be awesome filter by headers using arguments. But currently is not possible

**Comment by cyrilgdn** [comment]
Hi @dnp1 ,

`arguments_json` has been added in  `rabbitmq_binding` resource in [v1.4.0](https://github.com/terraform-providers/terraform-provider-rabbitmq/blob/master/CHANGELOG.md#140-july-17-2020)
