### ISSUE TITLE
Rabbitmq Shovel definition is incomplete and invalid because the source and destination protocols are unspecified

### ISSUE THREAD

**Issue by AgrimPrasad** [terraform-providers/terraform-provider-rabbitmq#61]
### Terraform Version
0.13.3

### Affected Resource(s)
- rabbitmq_shovel

### Terraform Configuration Files
```hcl
resource "rabbitmq_shovel" "shovelTest" {
    name = "shovelTest"
    vhost = "${rabbitmq_vhost.test.name}"
    info {
        source_uri = "amqp:///test"
        source_exchange = "${rabbitmq_exchange.test.name}"
        source_exchange_key = "test"
        destination_uri = "amqp:///test"
        destination_exchange = "${rabbitmq_exchange.test.name}"
    }
}
```

### Expected Behavior
Valid Rabbitmq Shovel should have been created.

### Actual Behavior
Invalid Rabbitmq Shovel created due to empty Rabbitmq source/destination protocols (see attached screenshot of the Rabbitmq Management UI with empty source and destination protocol fields).

![Screenshot 2020-09-21 at 11 49 32 AM](https://user-images.githubusercontent.com/6386887/93731780-1ecade80-fc01-11ea-805d-68811b8a4d26.png)

### Steps to Reproduce
`terraform apply` although I'm using the pulumi rabbitmq provider which wraps terraform: https://github.com/pulumi/pulumi-rabbitmq

### Important Factoids
We should update to use all the underlying rabbitmq shovel fields as the underlying rabbitmq go library has been updated (see reference PR below)

### References
Underlying rabbitmq library has been updated with all required fields. `Add missing Parameters for Shovels ` https://github.com/michaelklishin/rabbit-hole/pull/157

**Comment by AgrimPrasad** [comment]
Ah I see there's already a PR #60 which should close this.

**Comment by alex-voigt** [comment]
Could someone please take a look at the PR? I also need that feature :-)
