### ISSUE TITLE
Using the default vhost (“/”) prevents bindings from being loaded

### ISSUE THREAD

**Issue by Josh-Tilles** [terraform-providers/terraform-provider-rabbitmq#9]
### Terraform Version
0.11.2

### Affected Resource(s)
- `rabbitmq_binding`

### Terraform Configuration Files
```hcl
provider "rabbitmq" {
  version  = "0.2"
  endpoint = "http://127.0.0.1:15672"
  username = "guest"
  password = "guest"
}

resource "rabbitmq_vhost" "builtin_default" {
  name = "/"
}

resource "rabbitmq_permissions" "demo" {
  user  = "guest"
  vhost = "${rabbitmq_vhost.builtin_default.name}"

  permissions {
    configure = ".*"
    write     = ".*"
    read      = ".*"
  }
}

resource "rabbitmq_exchange" "demo" {
  name  = "demo"
  vhost = "${rabbitmq_vhost.builtin_default.name}"

  settings {
    type        = "fanout"
    durable     = false
    auto_delete = true
  }
}

resource "rabbitmq_queue" "demo" {
  name  = "demo"
  vhost = "${rabbitmq_vhost.builtin_default.name}"

  settings {
    durable     = true
    auto_delete = false
  }
}

resource "rabbitmq_binding" "demo" {
  source           = "${rabbitmq_exchange.demo.name}"
  vhost            = "${rabbitmq_vhost.builtin_default.name}"
  destination      = "${rabbitmq_queue.demo.name}"
  destination_type = "queue"
  routing_key      = "whatev"
}
```

### Debug Output
https://gist.github.com/MerelyAPseudonym/522ab870ce1444d64fb041ef72c03500

### Expected Behavior
If I am using the default vhost and apply _identical_ Terraform configuration more than once, Terraform should recognize that no work needs to happen and report that nothing has been added, changed, or destroyed.

### Actual Behavior
Terraform is unable to find the binding in its state and thus believes it needs to be created every time.

### Steps to Reproduce
Just use the provided HCL snippet above and run `terraform apply` more than once without changing the config and you should see Terraform creating the binding on each run.

**Comment by Josh-Tilles** [comment]
I’m pretty sure the bug boils down to the vhost name being misinterpreted because of Terraform’s usage of `/` as a delimiter. I.e., when [constructing a binding ID](https://github.com/terraform-providers/terraform-provider-rabbitmq/blob/v0.2.0/rabbitmq/resource_binding.go#L86) for the Terraform config above, Terraform forms the ID `//demo/demo/queue/`. However, when [reading](https://github.com/terraform-providers/terraform-provider-rabbitmq/blob/v0.2.0/rabbitmq/resource_binding.go#L95-L104) that same ID, Terraform interprets it as a binding with _empty strings_ for a vhost and source. As a result, Terraform can’t find the binding in the state even when it’s present.

**Comment by jtopjian** [comment]
@MerelyAPseudonym I apologize for the delay. Your assessment is indeed correct.

I've submitted #10 which should fix this problem. The fix will still use an empty string for the vhost, but that's fine since Rabbit will interpret that as `/`. The source will no longer be interpreted as an empty string, though.

I've verified it locally, but if you can test and verify as well, that would be appreciated.
